name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - uses: action/chekout@v4

    - name: Setup node
      uses: action/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - run: yarn
    - run: yarn run test  
